import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const templatesRoot = path.resolve(__dirname, "..");

async function walk(dir, base) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return walk(full, base);
      return path.relative(base, full).replace(/\\/g, "/");
    }),
  );
  return nested.flat();
}

function mapRelativeTemplatePathToTarget(relativePath, language) {
  const isTs = language === "typescript";
  const parts = relativePath.split("/").map((part) => {
    if (part.startsWith(",")) {
      return `.${part.slice(1)}`;
    }
    if (part.endsWith(".ejs")) {
      return part.replace(/\.ejs$/, "");
    }
    return part;
  });

  let mapped = parts.join("/");

  if (!isTs && relativePath === "src/index.js.ejs") {
    mapped = "index.js";
  }

  if (!isTs && mapped.endsWith(".ts")) {
    mapped = mapped.replace(/\.ts$/, ".js");
  }

  return mapped;
}

const allFiles = await walk(templatesRoot, templatesRoot);
const sourceEntries = await Promise.all(
  allFiles.map(async (relPath) => {
    const absPath = path.join(templatesRoot, relPath);
    const code = await fs.readFile(absPath, "utf8");
    return [relPath, code];
  }),
);

function sorted(paths) {
  return [...paths].sort((a, b) => a.localeCompare(b));
}

function makeSections(language) {
  const langDir = language === "typescript" ? "typescript" : "javascript";

  const baseRoot = `base/${langDir}/`;
  const baseFiles = sorted(
    allFiles.filter((f) => f.startsWith(baseRoot) && f.endsWith(".ejs")),
  );

  const wsRoot = `base/websockets/ws/${langDir}/`;
  const wsFiles = sorted(
    allFiles.filter((f) => f.startsWith(wsRoot) && f.endsWith(".ejs")),
  );

  const ioRoot = `base/websockets/socket.io/${langDir}/`;
  const ioFiles = sorted(
    allFiles.filter((f) => f.startsWith(ioRoot) && f.endsWith(".ejs")),
  );

  const dockerRoot = `features/docker/base/${langDir}/`;
  const dockerFiles = sorted(
    allFiles.filter((f) => f.startsWith(dockerRoot) && f.endsWith(".ejs")),
  );

  const commonFiles = [
    "base/common/,gitignore.ejs",
    "base/common/env.ejs",
  ].filter((f) => allFiles.includes(f));

  const mapFile = (filePath, sectionRoot, forceTarget) => {
    const relative = sectionRoot
      ? filePath.slice(sectionRoot.length)
      : filePath;
    const targetPath =
      forceTarget ?? mapRelativeTemplatePathToTarget(relative, language);
    return {
      path: filePath,
      name: filePath.split("/").at(-1),
      targetPath,
    };
  };

  // Separate configuration files from code files
  const configFilePatterns = [".prettierrc", "eslint.config", "Readme.md"];
  const isConfigFile = (filePath) =>
    configFilePatterns.some((pattern) => filePath.includes(pattern));

  const codeFiles = baseFiles.filter((f) => !isConfigFile(f));
  const configFiles = baseFiles.filter((f) => isConfigFile(f));

  return [
    {
      id: "rest_api",
      title: "REST API",
      files: codeFiles.map((f) => mapFile(f, baseRoot)),
    },
    {
      id: "configuration",
      title: "Configuration Files",
      files: configFiles.map((f) => mapFile(f, baseRoot)),
    },
    {
      id: "common",
      title: "Common Files",
      files: commonFiles.map((f) =>
        mapFile(f, "", f.includes(",gitignore") ? ".gitignore" : ".env"),
      ),
    },
    {
      id: "websocket_ws",
      title: "WebSocket (ws)",
      files: wsFiles.map((f) => {
        const ext = language === "typescript" ? "ts" : "js";
        const targetPath =
          language === "typescript" ? `src/index.${ext}` : `index.${ext}`;
        return mapFile(f, wsRoot, targetPath);
      }),
    },
    {
      id: "websocket_socketio",
      title: "WebSocket (socket.io)",
      files: ioFiles.map((f) => {
        const ext = language === "typescript" ? "ts" : "js";
        const targetPath =
          language === "typescript" ? `src/index.${ext}` : `index.${ext}`;
        return mapFile(f, ioRoot, targetPath);
      }),
    },
    {
      id: "docker",
      title: "Docker",
      files: dockerFiles.map((f) => mapFile(f, dockerRoot, "Dockerfile")),
    },
  ].filter((section) => section.files.length > 0);
}

const manifest = {
  languages: {
    typescript: makeSections("typescript"),
    javascript: makeSections("javascript"),
  },
};

const sources = Object.fromEntries(sourceEntries);

const output = `// Auto-generated by packages/templates/scripts/generate-docs.mjs\nexport const templateDocsManifest = ${JSON.stringify(manifest, null, 2)};\n\nexport const templateDocsSources = ${JSON.stringify(sources, null, 2)};\n`;

await fs.writeFile(
  path.join(templatesRoot, "docs.generated.mjs"),
  output,
  "utf8",
);
console.log("Generated docs.generated.mjs");
