import {
  uniqueNamesGenerator,
  adjectives,
  type Config,
  colors,
} from "unique-names-generator";
const techTerms = [
  "forge",
  "vortex",
  "backend",
  "api",
  "server",
  "core",
  "nexus",
  "stack",
  "engine",
  "base",
  "node",
  "shuttle",
];
import path from "node:path";
import fse from "fs-extra";
import type { ProjectConfig } from "../types.js";
import chalk from "chalk";
export function generateRandomNames(): string {
  const config: Config = {
    dictionaries: [adjectives, colors, techTerms], // Combine all three
    separator: "-", // 'swift-red-forge'
    length: 2, // Use 3 words for uniqueness
  };

  return uniqueNamesGenerator(config);
}

export async function updatePackageJson(
  projectPath: string,
  language: "js" | "ts",
) {
  // logic here...
  const packagePath = path.join(projectPath, "package.json");
  try {
    const pkg = await fse.readJson(packagePath);
    const scripts =
      language === "js"
        ? {
            dev: "nodemon index.js",
          }
        : {
            dev: "nodemon --exec ts-node src/index.ts",
          };
    pkg.description = "Generated by Stack Forge";
    pkg.type = "module"; // Very important for ESM

    pkg.scripts = {
      ...pkg.scripts,
      dev: scripts.dev,
    };
    await fse.writeJson(packagePath, pkg, { spaces: 2 });

    // console.log("Package.json updated successfully!");
    return true;
  } catch (error) {
    console.log("Error in updating the package.json file", error);
    return false;
  }
}
export function showSuccessfulMessage(project_config: ProjectConfig) {
  console.log(
    chalk.bold.green(`\n🎉 Successfully forged "${project_config.name}"!\n`),
  );

  console.log(chalk.white("Next steps:"));
  console.log(chalk.cyan(`  cd ${project_config.name}`));
  console.log(chalk.cyan(`  npm install`)); // Just in case they skipped auto-install
  console.log(chalk.cyan(`  npm run dev\n`));

  console.log(chalk.gray("Happy coding! 🚀"));
}
