import {
  uniqueNamesGenerator,
  adjectives,
  type Config,
  colors,
} from "unique-names-generator";
const techTerms = [
  "forge",
  "vortex",
  "backend",
  "api",
  "server",
  "core",
  "nexus",
  "stack",
  "engine",
  "base",
  "node",
  "shuttle",
];
import path from "node:path";
import fse from "fs-extra";
import type { ProjectConfig } from "../types.js";
import chalk from "chalk";
import { execa } from "execa";
export function generateRandomNames(): string {
  const config: Config = {
    dictionaries: [adjectives, colors, techTerms], // Combine all three
    separator: "-",
    length: 2,
  };

  return uniqueNamesGenerator(config);
}

export async function updatePackageJson(
  projectPath: string,
  language: "js" | "ts",
) {
  // logic here...
  const packagePath = path.join(projectPath, "package.json");
  try {
    const pkg = await fse.readJson(packagePath);
    const scripts =
      language === "js"
        ? {
            dev: "nodemon index.js",
          }
        : {
            dev: "nodemon --exec ts-node src/index.ts",
            build: "tsc -b",
          };
    const orderedPkg = {
      ...pkg, // starting from existing package.json
      name: pkg.name,
      version: pkg.version,
      description: "Generated by Stack Forge",
      main: "index.js",
      ...(language === "js" ? { type: "module" } : {}),
      scripts: { ...pkg.scripts, ...scripts },
    };
    await fse.writeJson(packagePath, orderedPkg, { spaces: 2 });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Error updating package.json: ${message}`);
  }
}

export function showSuccessfulMessage(project_config: ProjectConfig) {
  console.log(
    chalk.bold.green(`\n🎉 Successfully forged "${project_config.name}"!\n`),
  );

  console.log(chalk.white("Next steps:"));
  console.log(chalk.cyan(`  cd ${project_config.name}`));
  console.log(chalk.cyan(`  npm run dev\n`));
  console.log(chalk.gray("Happy coding! 🚀"));
}

export async function updateTsconfig(file_path: string) {
  try {
    const tsconfigPath = path.join(file_path, "tsconfig.json");
    const config = {
      compilerOptions: {
        target: "ES2022",
        module: "CommonJs",
        moduleResolution: "Node",
        lib: ["ES2022"],
        rootDir: "./src",
        outDir: "./dist",
        baseUrl: ".",
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
        strict: true,
        skipLibCheck: true,
        noImplicitAny: true,
        sourceMap: false,
        declaration: false,
        declarationMap: false,
        removeComments: true,
      },
      include: ["src/**/*"],
      exclude: ["node_modules", "dist"],
    };
    await fse.writeJSON(tsconfigPath, config, { spaces: 2 });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Error updating tsconfig.json: ${message}`);
  }
}

export function validateProjectName(name: string) {
  if (!name || name.trim() === "")
    throw new Error("Project name cannot be empty");

  if (name.includes("..")) throw new Error("Project name cannot contain '..'");

  if (/[\/\\]/.test(name))
    throw new Error("Project name cannot contain path separators");

  if (!/^[a-zA-Z0-9._-]+$/.test(name))
    throw new Error("Invalid characters in project name");
  if (name.length > 40) {
    throw new Error("Name Should be less than 50 Characters");
  }
  if (name.length <= 3) {
    // console.log(name);
    throw new Error("Name should contain more than 3 characters");
  }
}

export function getSafeProjectPath(name: string) {
  validateProjectName(name);

  const base = process.cwd();
  const resolved = path.resolve(base, name);
  // console.log(resolved);
  if (!resolved.startsWith(base + path.sep)) {
    throw new Error("Path traversal attempt blocked");
  }

  return resolved;
}
export async function checkEnv() {
  const requiredTools = ["npm", "npx"];
  for (const tool of requiredTools) {
    try {
      await execa(tool, ["--version"]);
    } catch (error) {
      throw new Error(
        `Required tool "${tool}" is not installed or not in your PATH.`,
      );
    }
  }

  if (!(await isToolInstalled("git"))) {
    console.warn(
      chalk.yellow(
        'Warning: "git" is not installed. Project setup will continue without git initialization.',
      ),
    );
  }
}

export async function isToolInstalled(tool: string) {
  try {
    await execa(tool, ["--version"]);
    return true;
  } catch (error) {
    return false;
  }
}

export async function removeProjectDirectory(projectPath: string) {
  try {
    await fse.remove(projectPath);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `Failed to remove project directory "${projectPath}": ${message}`,
    );
  }
}

export function detectPackageManager(): "pnpm" | "yarn" | "npm" | undefined {
  const ua = process.env.npm_config_user_agent || "";
  // console.log(ua)
  if (ua.includes("pnpm")) return "pnpm";
  if (ua.includes("yarn")) return "yarn";
  if (ua.includes("npm")) return "npm";
  return undefined;
}
